name: kidverse_ar
description: Minimal AR capability API (iOS ARKit, Android ARCore) via MethodChannel for KidVerse.
version: 0.1.0
publish_to: "none"

environment:
  sdk: 
    ">=2.17.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.kidverse.ar
        pluginClass: KidverseArPlugin
      ios:
        pluginClass: KidverseArPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

