name: kids_tutor
description: "An interactive learning app for children."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image: ^4.1.7
  collection: ^1.18.0
  camera: ^0.11.1
  permission_handler: ^12.0.1
  tflite_flutter: ^0.11.0
  vector_math: ^2.1.4
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  arkit_plugin: ^1.2.0
  flutter_tts: ^3.8.3
  http: ^1.1.0
  crypto: ^3.0.3
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/alphabets_pics/A/
    - assets/alphabets_pics/B/
    - assets/alphabets_pics/C/
    - assets/alphabets_pics/D/
    - assets/alphabets_pics/E/
    - assets/alphabets_pics/F/
    - assets/alphabets_pics/G/
    - assets/alphabets_pics/H/
    - assets/alphabets_pics/I/
    - assets/alphabets_pics/J/
    - assets/alphabets_pics/K/
    - assets/alphabets_pics/L/
    - assets/alphabets_pics/M/
    - assets/alphabets_pics/N/
    - assets/alphabets_pics/O/
    - assets/alphabets_pics/P/
    - assets/alphabets_pics/Q/
    - assets/alphabets_pics/R/
    - assets/alphabets_pics/S/
    - assets/alphabets_pics/T/
    - assets/alphabets_pics/U/
    - assets/alphabets_pics/V/
    - assets/alphabets_pics/W/
    - assets/alphabets_pics/X/
    - assets/alphabets_pics/Y/
    - assets/alphabets_pics/Z/
    - assets/3d_models/
    - lib/ml_models/labels.txt
    - lib/ml_models/labels_named.txt
    - lib/ml_models/model_unquant.tflite
    - assets/number_pics/0.png
    - assets/number_pics/1.png
    - assets/number_pics/2.png
    - assets/number_pics/3.png
    - assets/number_pics/4.png
    - assets/number_pics/5.png
    - assets/number_pics/6.png
    - assets/number_pics/7.png
    - assets/number_pics/8.png
    - assets/number_pics/9.png
    - assets/objects_pics/chair.png
    - assets/objects_pics/table.png
